---
- name:  Remove vsftpd
  hosts:  all
  gather_facts:  False

  tasks:
    - name:  Disable vsftpd firewall rule
      firewalld:
        service:  ftp
        immediate:  yes
        permanent:  yes
        state:  disabled

    - name:  Remove vsftpd software
      yum:
        name:  vsftpd
        state:  absent
