---
- name:  Install vsftpd
  hosts:  all
  gather_facts:  False

  tasks:
    - name:  Install vsftpd software
      yum:
        name:  vsftpd
        state:  present

    - name:  Disable vsftpd firewall rule
      firewalld:
        service:  ftp
        immediate:  yes
        permanent:  yes
        state:  enabled
